using FlightInformation.API.Controllers;
using System.Net;
using System.Net.Http.Json;

namespace FlightInformationAPI.IntegrationTests
{
    public class FlightInformationControllerTests : IClassFixture<CustomWebApplicationFactory>
    {
        private readonly CustomWebApplicationFactory _factory;

        public FlightInformationControllerTests(CustomWebApplicationFactory factory)
        {
            _factory = factory;
        }

        [Fact]
        public async Task GetFlights_Returns_Ok_And_SeededFlights()
        {
            // Arrange
            var client = _factory.CreateClient();

            // Act
            var response = await client.GetAsync("api/flights");

            // Assert
            response.EnsureSuccessStatusCode(); // StatusCode 200–299

            var flights = await response.Content.ReadFromJsonAsync<ICollection<Flight>>();

            Assert.NotNull(flights);
            Assert.NotEmpty(flights); // relies on your CsvSeeder seeding at least one flight
        }

        [Fact]
        public async Task GetFlight_Returns_NotFound_When_Id_Does_Not_Exist()
        {
            // Arrange
            var client = _factory.CreateClient();

            // Act
            var response = await client.GetAsync("api/flights/999999"); // some non-existing id

            // Assert
            Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);

            var error = await response.Content.ReadFromJsonAsync<ErrorResponse>();
            Assert.NotNull(error);
            Assert.Equal("Not Found", error!.Error);
            Assert.Contains("999999", error.Message);
        }

        [Fact]
        public async Task CreateFlight_Returns_BadRequest_When_Model_Is_Invalid()
        {
            // Arrange
            var client = _factory.CreateClient();

            // This should violate your FlightValidator rules
            var invalidFlight = new Flight
            {
                // TODO: adjust to actually violate your rules. Example if Airline is required:
                Airline = "",
                FlightNumber = "",
                DepartureAirport = "",
                ArrivalAirport = "",
                // Dates may be left default or invalid depending on your validator
            };

            // Act
            var response = await client.PostAsJsonAsync("api/flights", invalidFlight);

            // Assert
            Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);

            var error = await response.Content.ReadFromJsonAsync<ErrorResponse>();
            Assert.NotNull(error);
            Assert.Equal("Validation Failure", error!.Error);
            Assert.Equal("Invalid data format", error.Message);
            Assert.NotNull(error.Details);
            Assert.NotEmpty(error.Details); // validator errors should populate this
        }

        [Fact]
        public async Task CreateFlight_Then_GetFlights_Contains_NewFlight()
        {
            // Arrange
            var client = _factory.CreateClient();

            // Build a valid flight payload – tweak to satisfy FlightValidator
            var newFlight = new Flight
            {
                // Assuming Id is generated by DB/handler, leave as 0 or default
                FlightNumber = "INT-TEST-001",
                Airline = "TestAir",
                DepartureAirport = "AAA",
                ArrivalAirport = "BBB",
                DepartureTime = DateTime.UtcNow.AddHours(1),
                ArrivalTime = DateTime.UtcNow.AddHours(3),
                Status = FlightStatus.Scheduled // or whatever your enum type is named
            };

            // Act: create
            var createResponse = await client.PostAsJsonAsync("api/flights", newFlight);

            // Assert: create OK
            createResponse.EnsureSuccessStatusCode(); // expected 200 from controller
            var createBody = await createResponse.Content.ReadAsStringAsync();
            Assert.Contains("Flight created successfully", createBody);

            // Act: get all flights
            var getResponse = await client.GetAsync("api/flights");
            getResponse.EnsureSuccessStatusCode();

            var flights = await getResponse.Content.ReadFromJsonAsync<List<Flight>>();

            Assert.NotNull(flights);
            Assert.Contains(flights!, f => f.FlightNumber == "INT-TEST-001" && f.Airline == "TestAir");
        }

        [Fact]
        public async Task GetFlight_Returns_Ok_For_Existing_Flight()
        {
            // Arrange
            var client = _factory.CreateClient();

            // We don't know exact seeded ids, so:
            // 1. Get all flights
            var allResponse = await client.GetAsync("api/flights");
            allResponse.EnsureSuccessStatusCode();

            var flights = await allResponse.Content.ReadFromJsonAsync<List<Flight>>();
            Assert.NotNull(flights);
            Assert.NotEmpty(flights);

            var existing = flights![0];

            // Act: call GET /flights/{id}
            var getResponse = await client.GetAsync($"api/flights/{existing.Id}");

            // Assert
            getResponse.EnsureSuccessStatusCode();
            var returned = await getResponse.Content.ReadFromJsonAsync<Flight>();

            Assert.NotNull(returned);
            Assert.Equal(existing.Id, returned!.Id);
            Assert.Equal(existing.FlightNumber, returned.FlightNumber);
        }

        [Fact]
        public async Task DeleteFlight_Returns_NotFound_For_Unknown_Id()
        {
            // Arrange
            var client = _factory.CreateClient();

            // Act
            var response = await client.DeleteAsync("api/flights/999999");

            // Assert
            Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);

            var error = await response.Content.ReadFromJsonAsync<ErrorResponse>();
            Assert.NotNull(error);
            Assert.Equal("Not Found", error!.Error);
        }

        [Fact]
        public async Task SearchFlights_Returns_Ok_And_Collection()
        {
            // Arrange
            var client = _factory.CreateClient();

            // This relies on your SearchKeys binding to query string.
            // Adjust param names to match SearchKeys properties
            var response = await client.GetAsync("api/flights/search?airline=TestAir");

            // Assert
            response.EnsureSuccessStatusCode();

            var flights = await response.Content.ReadFromJsonAsync<ICollection<Flight>>();
            Assert.NotNull(flights);

            // Depending on your seed data, you may or may not assert non-empty here.
            // If CsvSeeder includes some flights for that airline, assert NotEmpty().
        }

        [Fact]
        public async Task UpdateFlight_Returns_BadRequest_When_Model_Invalid()
        {
            // Arrange
            var client = _factory.CreateClient();

            // Grab an existing flight id
            var allResponse = await client.GetAsync("api/flights");
            allResponse.EnsureSuccessStatusCode();
            var flights = await allResponse.Content.ReadFromJsonAsync<List<Flight>>();
            Assert.NotNull(flights);
            Assert.NotEmpty(flights);

            var existingId = flights![0].Id;

            // Build an invalid model (adjust to violate your validator)
            var invalidUpdate = new Flight
            {
                Id = existingId,
                FlightNumber = "", // invalid if required
                Airline = "",
            };

            // Act
            var response = await client.PutAsJsonAsync($"api/flights/{existingId}", invalidUpdate);

            // Assert
            Assert.Equal(HttpStatusCode.BadRequest, response.StatusCode);

            var error = await response.Content.ReadFromJsonAsync<ErrorResponse>();
            Assert.NotNull(error);
            Assert.Equal("Validation Failure", error!.Error);
        }

        [Fact]
        public async Task UpdateFlight_Returns_NotFound_When_Id_Does_Not_Exist()
        {
            // Arrange
            var client = _factory.CreateClient();

            var update = new Flight
            {
                Id = 999999,
                FlightNumber = "NO-EXIST",
                Airline = "NowhereAir",
                DepartureAirport = "AAA",
                ArrivalAirport = "BBB",
                DepartureTime = DateTime.UtcNow.AddHours(1),
                ArrivalTime = DateTime.UtcNow.AddHours(3),
                Status = FlightStatus.Scheduled
            };

            // Act
            var response = await client.PutAsJsonAsync("api/flights/999999", update);

            // Assert
            // This will be 404 only if your UpdateFlightCommandHandler returns a response with Flight = null.
            Assert.Equal(HttpStatusCode.NotFound, response.StatusCode);
        }
    }
}
